version: '3.8'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: vulnapp
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: vulnapp
    networks:
      - internal
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
    command: --performance_schema=off

  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - mysql
    networks:
      - internal
    volumes:
      - .:/app

volumes:
  postgres_data:
  mysql_data:

networks:
  internal:
    driver: bridge
